### ISSUE TITLE
Improvement: use `mat-color` instead of raw hex values

### ISSUE THREAD

**Issue by milesmatthias** [alexeagle/angular-bazel-example#270]
Use mat-color from the deep-purple built in theme instead of the raw hex values.

This is an uncompleted improvement todo from #262.

**Comment by zszafran** [comment]
It might be worth creating a theme.scss file anyways. I'm sure most people will want to do this with their own apps and having an example would be nice, especially since the scss import paths are kinda confusing. 

How I got it to work so far:
```scss
@import 'external/angular_material/src/lib/_theming.scss';
@include mat-core();

$app-primary: mat-palette($mat-deep-purple, 500, 100, 700);
$app-accent: mat-palette($mat-amber, A200, A100, A400);
$app-theme: mat-light-theme($app-primary, $app-accent);
@include angular-material-theme($app-theme);

&.dark-theme {
  $dark-primary: mat-palette($mat-deep-purple, 500, 100, 700);
  $dark-accent: mat-palette($mat-amber, A200, A100, A400);
  $dark-warn: mat-palette($mat-deep-orange, 500, 100, 700);
  $dark-theme: mat-dark-theme($dark-primary, $dark-accent, $dark-warn);
  @include angular-material-theme($dark-theme);
}
```

```python
sass_library(
    name = "theme",
    srcs = ["theme.scss"],
    deps = ["@angular_material//src/lib:theming_bundle"],
)

sass_binary(
    name = "main",
    src = "main.scss",
    deps = [":theme"],
)
```
